### ISSUE TITLE
[Feature Request] Support `bundleDependencies`

### ISSUE THREAD

**Issue by douglasg14b** [privatenumber/pkgroll#93]
### Feature request

`package.json` `bundleDependencies` lists dependencies that you wish to bundle with your package. It appears this proeprty is not utilized by pkgroll when making decisions on bundled/externalized dependencies.

### Motivations

See: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#bundledependencies

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment]
pkgroll doesn't read `bundleDependencies` because it enables a specific feature in `npm pack`:
https://docs.npmjs.com/cli/v10/configuring-npm/package-json#bundledependencies:~:text=This%20file%20contains%20the%20dependencies%20renderized%20and%20super%2Dstreams%20which%20can%20be%20installed%20in%20a%20new%20project%20by%20executing%20npm%20install%20awesome%2Dweb%2Dframework%2D1.0.0.tgz.

**Comment by privatenumber** [comment]
Closing for the above reason

**Comment by privatenumber** [comment]
Locking this thread as it’s being used to ask questions unrelated to the original topic.
